name: Integrity check

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4'] # 8.0

    name: PHP ${{ matrix.php }} tests
    steps:
      - name: Git clone
        uses: actions/checkout@master

      - name: Git update submodules
        run: |
          git submodule update --recursive

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install composer dependencies
        run: |
          composer install --no-interaction --prefer-dist
